terminate called after throwing an instance of 'sycl::_V1::exception'
  what():  Provided range is out of integer limits. Pass `-fno-sycl-id-queries-fit-in-int' to disable range check.
